### PR TITLE
fix: mempool occasional panics when store is ahead by a block

### LINKED ISSUE #1856: Mempool panics if chain desyncs
The block-producer can desync by one block if the store is under duress. An example is if the store takes longer than the gRPC connection timeout of 10s to apply the next block `N+1`.

The desync occurs because the block-producer assumes the block is cancelled and rolls back block `N+1`, however the store continues and commits the block. The block-producer is then one block behind the store. This was previously addressed in #1520 which enabled the block-producer to detect this and reset.

What was overlooked is that newly submitted transactions reach out to the store, and therefore get block `N+1` as the authenticated block height. This is correct. However, the mempool in the block-producer is only aware of `N+1` and we assert that the authentication height cannot exceed the local chain. This causes the submission to panic. Since this is an expected outcome (desync is valid), we should return an internal error instead.

### PR DESCRIPTION
**Pull request by Mirko-von-Leipzig**
This PR fixes an occasional panic when submitting a transaction or batch to the mempool.

The panic is handled correctly, that is, the mempool is not corrupted and continues to function. However, on v0.14 I've observed the panic unwinding holding onto the mempool lock for several seconds, making this more of a priority performance fix.

The bug occurs due to a race condition between a block being committed in the store and the mempool. A block first lands in the store, which means incoming transactions can get authenticated against `store.chain_tip`, while `mempool.chain_tip = store.chain_tip - 1`. The mempool then panics since its being given "bad" data from a trusted source.

This PR fixes this issue by having the mempool consider the current pending block as its chain tip,  instead of only the latest _committed_ block. This fixes the above issue, and also more correctly models things imo.

Fixes #1856

-----------

On a separate note, this does highlight that we should consider alternatives to a global mempool mutex.

### CODE REVIEW

File: crates/block-producer/src/mempool/mod.rs [hunk 1]
```diff
@@ -565,28 +566,30 @@ impl Mempool {
...
-            .checked_sub(self.committed_blocks.len() as u32)
-            .expect("number of committed blocks cannot exceed the chain tip");
+            .committed_blocks
+            .front()
+            .map_or(self.chain_tip(), |block| block.block_number)
+            .parent()
+            .unwrap_or_default();
 
-        if authentication_height < limit {
+        if authentication_height < dbg!(limit) {
```
Comment (igamigo) [inline crates/block-producer/src/mempool/mod.rs]: Guessing we want to remove this `dbg!()` (and the other one as well)

File: crates/block-producer/src/mempool/mod.rs [hunk 2]
```diff
@@ -389,7 +391,6 @@ impl Mempool {
     /// Panics if there is no matching block in flight.
     #[instrument(target = COMPONENT, name = "mempool.commit_block", skip_all)]
     pub fn commit_block(&mut self, block_header: BlockHeader) {
-        assert_eq!(self.chain_tip.child(), block_header.block_num());
```
Comment (igamigo) [inline crates/block-producer/src/mempool/mod.rs:392]: I think we can still keep this, no?

File: crates/block-producer/src/mempool/mod.rs [hunk 3]
```diff
@@ -203,9 +203,11 @@ impl Mempool {
 
     /// Returns the current chain tip height as seen by the mempool.
     ///
-    /// This reflects the latest committed block that the block producer is aware of.
+    /// This includes the block currently being built, if any.
     pub fn chain_tip(&self) -> BlockNumber {
```
Comment (igamigo) [inline crates/block-producer/src/mempool/mod.rs:207]: I think we may want to rename this. Reading the code, some places still use `self.chain_tip` and some others have moved to `self.chain_tip()`, so the difference is not immediately obvious to the reader. Or maybe the field itself could be renamed (`committed_chain_tip`?)

**Review by igamigo — APPROVED** [review]
LGTM! Left just a couple of minor comments. I think this does change the semantics of `add_transaction` and `add_user_batch` minimally, so I wonder if it's worth updating the comments/docs. For instance:

````protobuf
// Submits proven transaction to the Miden network. Returns the node's current block height.
rpc SubmitProvenTransaction(transaction.ProvenTransaction) returns (blockchain.BlockNumber) {}
````

now may return a block number that has not been committed yet (and may be reverted, etc.). The alternative is to roll back the return values in those functions, but I think in any case the returned value is more useful now (originally it was meant to signal, e.g. after which block number your note may be created).

>  this does highlight that we should consider alternatives to a global mempool mutex.

Agreed

**Review by sergerad — APPROVED** [review]

File: crates/block-producer/src/mempool/mod.rs (hunk 3 above)
Comment (Mirko-von-Leipzig) [reply crates/block-producer/src/mempool/mod.rs:207]: Ah. I think renaming the field is a great idea, thank you!

Comment (Mirko-von-Leipzig) [reply crates/block-producer/src/mempool/mod.rs:207]: @igamigo on the point of the RPC now returning the pending block height.. are you saying that's okay? This was an unintended side effect for me which I am going to revert.

But it sounds like you're in favor of it, or okay with it? My main concern would be that its possible this block does not become committed.

Comment (igamigo) [reply crates/block-producer/src/mempool/mod.rs:207]: Yeah, I went back and forth, but I think we want to remove this as well. As I said, that return value is supposed to be a hint for clients to know after which block their transaction would be committed (and so, when output notes would be created in the chain). Since that block number may not be committed, it may not be always accurate (ie we may return block 5 but it may turn out that the transaction we are submitting is committed in block 5).

**Comment by bobbinth** [comment]
> now may return a block number that has not been committed yet (and may be reverted, etc.). The alternative is to roll back the return values in those functions, but I think in any case the returned value is more useful now (originally it was meant to signal, e.g. after which block number your note may be created).

I would keep returning the latest committed block number - this way, there should be no ambiguity about whether we get latest committed or the upcoming block number. The client can then make adjustments (if any needed) to estimate which block the transaction is going to land in.

**Comment by Mirko-von-Leipzig** [comment]
> > now may return a block number that has not been committed yet (and may be reverted, etc.). The alternative is to roll back the return values in those functions, but I think in any case the returned value is more useful now (originally it was meant to signal, e.g. after which block number your note may be created).
> 
> I would keep returning the latest committed block number - this way, there should be no ambiguity about whether we get latest committed or the upcoming block number. The client can then make adjustments (if any needed) to estimate which block the transaction is going to land in.

I've reverted to this behaviour.
