### PR TITLE
Replace bundled command with compose

### LINKED ISSUE #1765: Replace bundled command
# Replace `bundled` command with local multi-process deployment

## Summary

Remove the `miden-node bundled` command and replace it with a proper local deployment mechanism that runs each node component as a separate (containerized) process. This ensures that local testing and development imitates production-style deployment as closely as possible.

## Motivation

The `bundled` command runs all node components (Store, RPC, Block Producer, Validator, NTX Builder) as tasks within a single process. While convenient, this approach has several drawbacks:

- **Hides the real architecture.** Developers don't validate aspects of the system that are affected by a distributed deployment topology.
- **Masks failure modes.** A single process with fail-fast semantics (`JoinSet::join_next`) doesn't exercise the partial-failure and reconnection scenarios that occur in production.
- **Adds unnecessary complexity and maintenance overhead.** Developers have to consider both bundled and non-bundled configurations when implementing new features.
- **Prevents independent scaling/restart.** You can't restart or replace a single component without tearing down the entire node.
- **Diverges from production.** The bundled mode uses `127.0.0.1:0` for internal endpoints and passes `TcpListener` handles directly, which is fundamentally different from how components connect in a distributed deployment. We also deploy containerized versions of the stack in production.

A local multi-process deployment tool would provide a more realistic and useful development/testing experience while still being easy to use.

### The `bundled` command

Located in `bin/node/src/commands/bundled.rs`, it provides two subcommands:

- **`bundled bootstrap`** — initializes the store database with a genesis block.
- **`bundled start`** — spawns all components as tokio tasks in a `JoinSet`, binds internal gRPC endpoints to random localhost ports, and crashes if any component exits.

### Individual component commands

Each component already has its own CLI subcommand under `miden-node`:

| Component | Command | Key flags |
|---|---|---|
| Store | `miden-node store start` | `--rpc.url`, `--block-producer.url`, `--ntx-builder.url`, `--data-directory` |
| RPC | `miden-node rpc start` | `--url`, `--store.url`, `--block-producer.url`, `--validator.url` |
| Block Producer | `miden-node block-producer start` | `--store.url`, `--validator.url` |
| Validator | `miden-node validator start` | `--data-directory` |
| NTX Builder | **none** (embedded in bundled only) | `--store.url`, `--block-producer.url`, `--validator.url`, `--ntx-builder.data-directory` |

> **Note:** The NTX Builder currently has no standalone CLI subcommand — it is only launched as part of `bundled start`. A new `miden-node ntx-builder start` subcommand will need to be added before it can run as its own process.

Running these individually today requires manually coordinating all URLs and ensuring correct startup order (store must be available before other components connect).

### Existing Docker support

- A `Dockerfile` exists at `bin/node/Dockerfile` that builds the `miden-node` binary.
- `make docker-build-node` and `make docker-run-node` targets exist but only run a single container.
- **No `docker-compose.yml` exists.** There is no multi-container orchestration.

### 1. Remove the `bundled` command

Delete the `bundled` subcommand and its associated code:

- `bin/node/src/commands/bundled.rs`
- Related CLI variants, config structs (`BundledValidatorConfig`), and wiring in `bin/node/src/commands/mod.rs`
- Update the systemd service file (`packaging/node/miden-node.service`) which currently runs `bundled start`
- Update operator documentation (`docs/external/src/operator/`) to remove bundled references

### 2. Add a local multi-process deployment tool

Replace bundled with a tool that launches each component as a **separate OS process** with pre-configured, well-known ports. Two main options are considered:

---

### Option A: `docker-compose`

Add a `docker-compose.yml` at the repo root that defines one service per component.

**Sketch:**

```yaml
services:
  store:
    build:
      context: .
      dockerfile: bin/node/Dockerfile
    command: >
      miden-node store start
        --rpc.url http://0.0.0.0:50051
        --block-producer.url http://0.0.0.0:50052
        --ntx-builder.url http://0.0.0.0:50053
        --data-directory /data
    volumes:
      - store-data:/data
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 5s

  block-producer:
    build:
      context: .
      dockerfile: bin/node/Dockerfile
    command: >
      miden-node block-producer start http://0.0.0.0:50054
        --store.url http://store:50052
        --validator.url http://validator:50055
    depends_on:
      store:
        condition: service_healthy

  validator:
    build:
      context: .
      dockerfile: bin/node/Dockerfile
    command: >
      miden-node validator start http://0.0.0.0:50055
        --data-directory /data
    volumes:
      - validator-data:/data

  rpc:
    build:
      context: .
      dockerfile: bin/node/Dockerfile
    command: >
      miden-node rpc start
        --url http://0.0.0.0:57291
        --store.url http://store:50051
        --block-producer.url http://block-producer:50054
        --validator.url http://validator:50055
    ports:
      - "57291:57291"
    depends_on:
      store:
        condition: service_healthy

  ntx-builder:
    build:
      context: .
      dockerfile: bin/node/Dockerfile
    command: >
      miden-node ntx-builder start
        --store.url http://store:50053
        --block-producer.url http://block-producer:50054
        --validator.url http://validator:50055
        --ntx-builder.data-directory /data
    volumes:
      - ntx-builder-data:/data
    depends_on:
      store:
        condition: service_healthy

volumes:
  store-data:
  validator-data:
  ntx-builder-data:
```

**Pros:**
- Industry standard, most developers already know it
- Zero additional tooling — Docker is the only dependency
- Simple YAML, easy to read and modify
- `docker compose up` / `docker compose down` is familiar
- Existing `Dockerfile` can be reused as-is
- Supports `depends_on` with health checks for startup ordering

**Cons:**
- Rebuild cycle for code changes is slower (must rebuild container image)
- Debugging is slightly less convenient than native processes (need `docker exec` or remote debugger)
- Doesn't support running a mix of local binaries and containers easily

---

### Option B: Kurtosis

Use [Kurtosis](https://www.kurtosis.com/) to define a package (Starlark) that orchestrates the node stack.

**Sketch:**

```python
def run(plan):
    store = plan.add_service(
        name="store",
        config=ServiceConfig(
            image=ImageBuildSpec(image_name="miden-node", build_context_dir="."),
            cmd=["miden-node", "store", "start", ...],
            ports={"rpc": PortSpec(50051), "bp": PortSpec(50052), "ntx": PortSpec(50053)},
        ),
    )

    validator = plan.add_service(
        name="validator",
        config=ServiceConfig(
            image="miden-node",
            cmd=["miden-node", "validator", "start", ...],
            ports={"grpc": PortSpec(50055)},
        ),
    )

    block_producer = plan.add_service(
        name="block-producer",
        config=ServiceConfig(
            image="miden-node",
            cmd=["miden-node", "block-producer", "start",
                 "--store.url", "http://{}:{}".format(store.ip_address, 50052),
                 "--validator.url", "http://{}:{}".format(validator.ip_address, 50055)],
            ports={"grpc": PortSpec(50054)},
        ),
    )

    plan.add_service(
        name="rpc",
        config=ServiceConfig(
            image="miden-node",
            cmd=["miden-node", "rpc", "start",
                 "--url", "http://0.0.0.0:57291",
                 "--store.url", "http://{}:{}".format(store.ip_address, 50051),
                 "--block-producer.url", "http://{}:{}".format(block_producer.ip_address, 50054),
                 "--validator.url", "http://{}:{}".format(validator.ip_address, 50055)],
            ports={"rpc": PortSpec(57291, transport_protocol="TCP")},
        ),
    )

    plan.add_service(
        name="ntx-builder",
        config=ServiceConfig(
            image="miden-node",
            cmd=["miden-node", "ntx-builder", "start",
                 "--store.url", "http://{}:{}".format(store.ip_address, 50053),
                 "--block-producer.url", "http://{}:{}".format(block_producer.ip_address, 50054),
                 "--validator.url", "http://{}:{}".format(validator.ip_address, 50055),
                 "--ntx-builder.data-directory", "/data"],
        ),
    )
```

**Pros:**
- Programmable topology (Starlark) — can parameterize number of validators, toggle NTX builder, etc.
- Built-in service dependency resolution and health checking
- Designed for multi-service dev/test environments
- Enclave isolation — multiple instances can run side-by-side without port conflicts
- Good for CI — reproducible, hermetic environments
- Can be extended for multi-node / network testing scenarios

**Cons:**
- Requires installing Kurtosis CLI — an additional dependency most developers won't have
- Starlark is less familiar than YAML for most developers
- Smaller community and ecosystem compared to Docker Compose
- Adds a layer of abstraction that may complicate debugging
- Kurtosis itself is a relatively young tool — risk of API changes or reduced maintenance

---

## Work items (assuming docker-compose approach)

- [ ] Add a standalone `miden-node ntx-builder start` CLI subcommand
- [ ] Add `docker-compose.yml` with all node components as separate services
- [ ] Add a bootstrap init-container or script that runs `miden-node store bootstrap` before the stack starts
- [ ] Add `make compose-up` / `make compose-down` targets to the Makefile
- [ ] Update operator documentation to describe the new deployment workflow
- [ ] Remove `bundled.rs` and all associated CLI/config code
- [ ] Remove all system service files apart from validator. Also consider deploying validator with Docker instead.

### PR DESCRIPTION
**Pull request by sergerad**
## Context

We want to replace the bundled command with a docker-compose deployment for local development.

Closes #1765 and #1306.

## Changes

- Remove the `bundled` command which ran all components in a single process
- Add `ntx-builder` as a standalone CLI subcommand
- Add `docker-compose.yml` with individual services: store, validator, block-producer, rpc, ntx-builder
- Add a separate `genesis` compose profile that wipes volumes and bootstraps a fresh network
- Update Makefile: `make compose-genesis` (wipe + bootstrap), `make compose-up` (start), `make compose-down` (stop), `make compose-logs` (follow logs)
- Add `scripts/run-node.sh` to run all components as separate processes without Docker.

### CODE REVIEW

**Review by SantiagoPittella — COMMENTED** [review]
Did not review it yet, but tried running `docker-compose up` and got this errors:
```
rpc-1 exited with code 2
ntx-builder-1 exited with code 2
block-producer-1 exited with code 2
validator-1 exited with code 2
```

**Comment by sergerad** [comment]
> I have not yet read through this, but I don't think we can actively remove the `bundled` command just yet, until we are extremely certain that all things work correctly as separate components.

My intention with this PR is to have it working against the integration test suite so it will at least be working for local dev use case. As for deployment to devnet, yea we need to make sure we merge this at a moment that makes sense in terms of our planned releases.

**Comment by SantiagoPittella** [comment]
When trying the `make compose-genesis` -> `make compose-up` -> `make compose-down` -> `make compose-logs` flow I received:

```
$ make compose-genesis

...
 ✔ Volume "miden-node_store-data"    Created                                                                                                                                           0.0s
 ✔ Volume "miden-node_accounts"      Created                                                                                                                                           0.0s
Bootstrapping validator (creating genesis block)...
error: unrecognized subcommand 'bootstrap'

Usage: miden-node validator <COMMAND>

For more information, try '--help'.

make: *** [compose-genesis] Error 2
```

And after running `make compose-logs` this is the output:

```
$ make compose-logs
docker compose logs -f
```

If I check the containers I see the following errors:
Screenshot 2026-03-25 at 17 18 04
Screenshot 2026-03-25 at 17 18 30

File: bin/node/src/commands/ntx_builder.rs [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+            block_producer_url,
+            validator_url,
+            tx_prover_url,
+            ticker_interval: _,
+            script_cache_size,
+            idle_timeout,
+            max_account_crashes,
+            max_tx_cycles,
+            data_directory,
+            enable_otel: _,
```
Comment (SantiagoPittella) [inline bin/node/src/commands/ntx_builder.rs]: We are discarding  `ticker_interval` and `enable_otel`. Should be handled?

File: scripts/run-node.sh [hunk 2]
```diff
@@ -0,0 +1,103 @@
+#!/usr/bin/env bash
+set -euo pipefail
+
+# Configuration
+BINARY="./target/debug/miden-node"
```
Comment (SantiagoPittella) [inline scripts/run-node.sh]: This is hardcoding debug mode. Should be replaced with production? Or maybe with something like an env var?

**Review by SantiagoPittella — APPROVED** [review]
Manual tests running the docker compose and client's integration tests worked properly.

File: bin/node/src/commands/ntx_builder.rs (hunk 1 above)
Comment (sergerad) [reply bin/node/src/commands/ntx_builder.rs]: ticker_interval is unused in next too so I have removed it. enable_otel is used this way in other subcommands (its handled earlier and discarded here)
```rust
            Command::NtxBuilder(subcommand) => subcommand.is_open_telemetry_enabled(),
```

File: bin/node/Dockerfile [hunk 3]
```diff
@@ -28,7 +28,7 @@ COPY . .
 RUN cargo build --release --locked --bin miden-node
 
 # Base line runtime image with runtime dependencies installed.
-FROM debian:bullseye-slim AS runtime-base
+FROM debian:bookworm-slim AS runtime-base
```
Comment (Mirko-von-Leipzig) [inline bin/node/Dockerfile:31]: Just a random update? Or is this required?

File: scripts/run-node.sh
Comment (Mirko-von-Leipzig) [inline scripts/run-node.sh:1]: Why does this require AWS? The docker compose isn't intended for production usage.

**Review by Mirko-von-Leipzig — COMMENTED** [review]
Minor comments; otherwise I _think_ this looks okay, though I haven't given this a super thorough review.

File: bin/node/Dockerfile (hunk 3 above)
Comment (sergerad) [reply bin/node/Dockerfile:31]: To match the above `FROM rust:1.93-slim-bookworm AS chef`

File: scripts/run-node.sh
Comment (sergerad) [reply scripts/run-node.sh:1]: Thanks I have made it optional now. I use it to test the AWS flow with a testing/dev kms key id

File: docs/external/src/operator/usage.md [hunk 4]
```diff
@@ -110,18 +102,82 @@ path = "eth_faucet.mac"
...
+
+### Running components individually
+
+A convenience script is provided that bootstraps and starts all components as separate processes:
+
+```sh
+export AWS_REGION=eu-north-1
+export KMS_KEY_ID=<your-kms-key-id>
+./scripts/run-node.sh
+```
```
Comment (bobbinth) [inline docs/external/src/operator/usage.md:141]: Does this mean we cannot run the node outside of AWS?

Comment (sergerad) [reply docs/external/src/operator/usage.md:141]: This is only for specifying a KMS key to be used for block signing. Which basically no one will use here - maybe we should omit it from the readme tbh.

Comment (bobbinth) [reply docs/external/src/operator/usage.md:141]: I'd keep it but provide a couple of sentences for explanation to make things a bit more clear.
